all: pipe1 pipe2 pipe3 pipe4 pipe5

pipe1: pipe1.c
	gcc -g -O0 -o pipe1 pipe1.c

pipe2: pipe2.c
	gcc -g -O0 -o pipe2 pipe2.c

pipe3: pipe3.c
	gcc -g -O0 -o pipe3 pipe3.c

pipe4: pipe4.c
	gcc -g -O0 -o pipe4 pipe4.c

pipe5: pipe5.c
	gcc -g -O0 -o pipe5 pipe5.c

clean:
	rm -rf *.o pipe1 pipe2 pipe3 pipe4 pipe5


