a.out : atexit1 atexit2 atexit3

atexit1: atexit1.c
	gcc -g -O0 -o atexit1 atexit1.c

atexit2: atexit2.c
	gcc -g -O0 -o atexit2 atexit2.c

atexit3: atexit3.c
	gcc -g -O0 -o atexit3 atexit3.c


clean: 
	rm -rf *.o atexit1 atexit2 atexit3
